version: '3'

services:
    # Base de données PostgreSQL (Commune aux deux projets)
    db:
        image: postgres:15.4-bullseye
        volumes:
            - ./app-data/data/postgres/logs:/var/log/postgresql
            - ./app-data/data/postgres/data:/var/lib/postgresql/data
            - ./app-data/schemas:/docker-entrypoint-initdb.d/
            - ./app-data/backup:/backup/
            - ./app-data/scripts:/scripts
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=latina
            - POSTGRES_USER=alexis
            - POSTGRES_DB=db

    # Interface d'administration de la base de données pgAdmin (Commune aux deux projets)
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:7.6
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@local.int
            PGADMIN_DEFAULT_PASSWORD: latina
            PG_DATABASE: db
            PG_USER: alexis
            PG_PASSWORD: latina
        volumes:
            - ./app-data/data/pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        links:
            - db:postgres